
import type { Product, User } from './types';

export const initialUsers: (User & { passwordHash: string })[] = [
  {
    id: 'user-1',
    username: 'SustainableStacy',
    email: 'stacy@example.com',
    passwordHash: 'password123',
  },
  {
    id: 'user-2',
    username: 'EcoEthan',
    email: 'ethan@example.com',
    passwordHash: 'password123',
  },
];

export const initialProducts: Product[] = [
  {
    id: 'prod-1',
    userId: 'user-2',
    title: 'Vintage Leather Jacket',
    description: 'A beautifully worn-in vintage leather jacket. Classic style, perfect for all seasons. Minor scuffs add to the character.',
    category: 'Fashion',
    price: 75.0,
    imageUrl: 'https://picsum.photos/seed/jacket/600/400',
    quantity: 1,
    condition: 'Used - Good',
    brand: 'Retro Wear',
    color: 'Brown',
    material: 'Leather',
    originalPackaging: false,
    manualIncluded: false,
    workingCondition: 'Fully functional, all zippers and buttons work.'
  },
  {
    id: 'prod-2',
    userId: 'user-1',
    title: 'Antique Wooden Chair',
    description: 'A solid oak chair with intricate carvings. Restored to its former glory. A statement piece for any room.',
    category: 'Home Goods',
    price: 120.0,
    imageUrl: 'https://picsum.photos/seed/chair/600/400',
    quantity: 1,
    condition: 'Used - Like New',
    brand: 'Heirloom Furniture',
    yearOfManufacture: 1920,
    dimensions: '20" x 18" x 38"',
    weight: '15 lbs',
    material: 'Oak',
    color: 'Dark Wood',
    originalPackaging: false,
    manualIncluded: false,
    workingCondition: 'Sturdy and recently refinished.'
  },
  {
    id: 'prod-3',
    userId: 'user-2',
    title: 'First Edition Novel',
    description: 'A rare first edition copy of a classic novel. In excellent condition for its age. A must-have for collectors.',
    category: 'Books',
    price: 250.0,
    imageUrl: 'https://picsum.photos/seed/book/600/400',
    quantity: 1,
    condition: 'Used - Good',
    originalPackaging: false,
    manualIncluded: false,
    workingCondition: 'Pages are clean, binding is tight.'
  },
  {
    id: 'prod-4',
    userId: 'user-1',
    title: 'Retro Bluetooth Speaker',
    description: 'A modern speaker with a cool retro design. Great sound quality and long battery life. Connects via Bluetooth.',
    category: 'Electronics',
    price: 45.0,
    imageUrl: 'https://picsum.photos/seed/speaker/600/400',
    quantity: 1,
    condition: 'New',
    brand: 'AudioVibes',
    model: 'RetroBlast 5000',
    color: 'Teal',
    originalPackaging: true,
    manualIncluded: true,
    workingCondition: 'Brand new in box, works perfectly.'
  },
  {
    id: 'prod-5',
    userId: 'user-1',
    title: 'Hand-knitted Wool Scarf',
    description: 'A cozy and warm scarf, hand-knitted with 100% merino wool. The perfect accessory for cold weather.',
    category: 'Fashion',
    price: 30.0,
    imageUrl: 'https://picsum.photos/seed/scarf/600/400',
    quantity: 5,
    condition: 'New',
    material: 'Merino Wool',
    color: 'Cream',
    originalPackaging: false,
    manualIncluded: false,
    workingCondition: 'Newly made.'
  },
  {
    id: 'prod-6',
    userId: 'user-2',
    title: 'Set of Ceramic Mugs',
    description: 'Four handmade ceramic mugs with a unique glaze. Dishwasher and microwave safe. Each one is slightly different.',
    category: 'Home Goods',
    price: 40.0,
    imageUrl: 'https://picsum.photos/seed/mugs/600/400',
    quantity: 1,
    condition: 'New',
    material: 'Ceramic',
    color: 'Blue/Green',
    originalPackaging: false,
    manualIncluded: false,
    workingCondition: 'Brand new, no chips or cracks.'
  },
  {
    id: 'prod-8',
    userId: 'user-2',
    title: 'Decorative Wall Mirror',
    description: 'Elegant round wall mirror with a gold-finished frame. Adds charm and character to any living space.',
    category: 'Home Goods',
    price: 85.0,
    imageUrl: 'https://picsum.photos/seed/mirror/600/400',
    quantity: 1,
    condition: 'New',
    material: 'Glass and Metal',
    color: 'Gold',
    originalPackaging: true,
    manualIncluded: true,
    workingCondition: 'Brand new, no scratches.'
  },
  {
    id: 'prod-9',
    userId: 'user-1',
    title: 'Collector’s Edition Poetry Book',
    description: 'A beautifully bound poetry collection featuring renowned poets. Limited collector’s edition.',
    category: 'Books',
    price: 60.0,
    imageUrl: 'https://picsum.photos/seed/poetry/600/400',
    quantity: 1,
    condition: 'New',
    originalPackaging: true,
    manualIncluded: false,
    workingCondition: 'Pristine condition.'
  },
  {
    id: 'prod-10',
    userId: 'user-2',
    title: 'Wireless Earbuds',
    description: 'Compact and sleek wireless earbuds with noise cancellation and charging case. Great sound quality.',
    category: 'Electronics',
    price: 55.0,
    imageUrl: 'https://picsum.photos/seed/earbuds/600/400',
    quantity: 1,
    condition: 'New',
    brand: 'SoundPlus',
    model: 'SP1000',
    color: 'Black',
    originalPackaging: true,
    manualIncluded: true,
    workingCondition: 'New, works perfectly.'
  },
  {
    id: 'prod-11',
    userId: 'user-1',
    title: 'Vintage Transistor Radio',
    description: 'A classic 1960s transistor radio. Fully functional and picks up AM stations. A great decorative and functional piece.',
    category: 'Electronics',
    price: 65.0,
    imageUrl: 'https://picsum.photos/seed/radio/600/400',
    quantity: 1,
    condition: 'Used - Good',
    brand: 'General Electric',
    model: 'P-808',
    color: 'Beige',
    originalPackaging: false,
    manualIncluded: false,
    workingCondition: 'Works well, some static as expected with vintage radios.'
  },
  {
    id: 'prod-12',
    userId: 'user-2',
    title: 'Classic Philosophy Book Set',
    description: 'A set of three essential philosophy books: "Meditations" by Marcus Aurelius, "The Republic" by Plato, and "Nicomachean Ethics" by Aristotle.',
    category: 'Books',
    price: 40.0,
    imageUrl: 'https://picsum.photos/seed/philosophy/600/400',
    quantity: 1,
    condition: 'Used - Like New',
    originalPackaging: false,
    manualIncluded: false,
    workingCondition: 'Excellent condition, no markings or bent pages.'
  }
];
